---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - ../.env
    environment:
      - PUID=1007
      - PGID=1001
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${MEDIA}/tv:/tv
      - ${DOWNLOADS}:/downloads 
    ports:
      - 8989:8989
    restart: always