---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1003
      - PGID=1101
      - TZ=$(cat /etc/timezone)
    volumes:
      - $CONFIG/sonarr:/config
      - $MEDIA/tv:/tv
      - $DOWNLOADS:/downloads 
    ports:
      - 8989:8989
    restart: always