---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1002
      - PGID=1001
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/jellyfin:/config
      - ${MEDIA}/tv:/data/tvshows,ro
      - ${MEDIA}/movies:/data/movies,ro
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    ports:
      - 8096:8096
    restart: always