---
version: "2.1"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1003
      - PGID=1001
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/lidarr:/config
      - ${MEDIA}/music:/music
      - ${DOWNLOADS}:/downloads
    ports:
      - 8686:8686
    restart: always