---
version: "2.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    env_file:
      - ./apps/.env
    environment:
      - PUID=1005
      - PGID=1001
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/readarr:/config
      - ${MEDIA}/books:/books 
      - ${DOWNLOADS}:/downloads
    ports:
      - 8787:8787
    restart: always