---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1002
      - PGID=1101
      - TZ=$(cat /etc/timezone)
      - TRANSMISSION_WEB_HOME=/flood-for-transmission/
    volumes:
      - $CONFIG/transmission:/config
      - $DOWNLOADS:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always 