---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    env_file:
      - ../.env
    environment:
      - PUID=1207
      - PGID=1100
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME=/flood-for-transmission/
    volumes:
      - ${CONFIG}/apps/transmission:/config
      - ${DOWNLOADS}/:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always 