---
version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    env_file:
      - ../.env
    container_name: calibre
    environment:
      - PUID=1200
      - PGID=1100
      - TZ=${TZ}
    volumes:
      - ${MEDIA}/calibre:/config
    ports:
      - 8081:8080
      - 8082:8081
    restart: always